// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pb/templates/template.v1.proto

package templates

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AlertTemplateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AlertTemplateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AlertTemplateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AlertTemplateRequestMultiError, or nil if none found.
func (m *AlertTemplateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AlertTemplateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	// no validation rules for Use

	// no validation rules for Tpl

	// no validation rules for Url

	// no validation rules for Phone

	// no validation rules for Email

	// no validation rules for Secret

	// no validation rules for At

	if len(errors) > 0 {
		return AlertTemplateRequestMultiError(errors)
	}

	return nil
}

// AlertTemplateRequestMultiError is an error wrapping multiple validation
// errors returned by AlertTemplateRequest.ValidateAll() if the designated
// constraints aren't met.
type AlertTemplateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AlertTemplateRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AlertTemplateRequestMultiError) AllErrors() []error { return m }

// AlertTemplateRequestValidationError is the validation error returned by
// AlertTemplateRequest.Validate if the designated constraints aren't met.
type AlertTemplateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AlertTemplateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AlertTemplateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AlertTemplateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AlertTemplateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AlertTemplateRequestValidationError) ErrorName() string {
	return "AlertTemplateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AlertTemplateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAlertTemplateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AlertTemplateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AlertTemplateRequestValidationError{}

// Validate checks the field values on AlertTemplateReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AlertTemplateReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AlertTemplateReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AlertTemplateReplyMultiError, or nil if none found.
func (m *AlertTemplateReply) ValidateAll() error {
	return m.validate(true)
}

func (m *AlertTemplateReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AlertTemplateReplyMultiError(errors)
	}

	return nil
}

// AlertTemplateReplyMultiError is an error wrapping multiple validation errors
// returned by AlertTemplateReply.ValidateAll() if the designated constraints
// aren't met.
type AlertTemplateReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AlertTemplateReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AlertTemplateReplyMultiError) AllErrors() []error { return m }

// AlertTemplateReplyValidationError is the validation error returned by
// AlertTemplateReply.Validate if the designated constraints aren't met.
type AlertTemplateReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AlertTemplateReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AlertTemplateReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AlertTemplateReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AlertTemplateReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AlertTemplateReplyValidationError) ErrorName() string {
	return "AlertTemplateReplyValidationError"
}

// Error satisfies the builtin error interface
func (e AlertTemplateReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAlertTemplateReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AlertTemplateReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AlertTemplateReplyValidationError{}

// Validate checks the field values on DeleteTemplateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteTemplateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteTemplateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteTemplateRequestMultiError, or nil if none found.
func (m *DeleteTemplateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteTemplateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteTemplateRequestMultiError(errors)
	}

	return nil
}

// DeleteTemplateRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteTemplateRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteTemplateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteTemplateRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteTemplateRequestMultiError) AllErrors() []error { return m }

// DeleteTemplateRequestValidationError is the validation error returned by
// DeleteTemplateRequest.Validate if the designated constraints aren't met.
type DeleteTemplateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteTemplateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteTemplateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteTemplateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteTemplateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteTemplateRequestValidationError) ErrorName() string {
	return "DeleteTemplateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteTemplateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteTemplateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteTemplateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteTemplateRequestValidationError{}

// Validate checks the field values on DeleteTemplateReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteTemplateReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteTemplateReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteTemplateReplyMultiError, or nil if none found.
func (m *DeleteTemplateReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteTemplateReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteTemplateReplyMultiError(errors)
	}

	return nil
}

// DeleteTemplateReplyMultiError is an error wrapping multiple validation
// errors returned by DeleteTemplateReply.ValidateAll() if the designated
// constraints aren't met.
type DeleteTemplateReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteTemplateReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteTemplateReplyMultiError) AllErrors() []error { return m }

// DeleteTemplateReplyValidationError is the validation error returned by
// DeleteTemplateReply.Validate if the designated constraints aren't met.
type DeleteTemplateReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteTemplateReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteTemplateReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteTemplateReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteTemplateReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteTemplateReplyValidationError) ErrorName() string {
	return "DeleteTemplateReplyValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteTemplateReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteTemplateReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteTemplateReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteTemplateReplyValidationError{}

// Validate checks the field values on UpdateTemplateBatchRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateTemplateBatchRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateTemplateBatchRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateTemplateBatchRequestMultiError, or nil if none found.
func (m *UpdateTemplateBatchRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateTemplateBatchRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Type

	// no validation rules for Use

	// no validation rules for Content

	if len(errors) > 0 {
		return UpdateTemplateBatchRequestMultiError(errors)
	}

	return nil
}

// UpdateTemplateBatchRequestMultiError is an error wrapping multiple
// validation errors returned by UpdateTemplateBatchRequest.ValidateAll() if
// the designated constraints aren't met.
type UpdateTemplateBatchRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateTemplateBatchRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateTemplateBatchRequestMultiError) AllErrors() []error { return m }

// UpdateTemplateBatchRequestValidationError is the validation error returned
// by UpdateTemplateBatchRequest.Validate if the designated constraints aren't met.
type UpdateTemplateBatchRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateTemplateBatchRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateTemplateBatchRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateTemplateBatchRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateTemplateBatchRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateTemplateBatchRequestValidationError) ErrorName() string {
	return "UpdateTemplateBatchRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateTemplateBatchRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateTemplateBatchRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateTemplateBatchRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateTemplateBatchRequestValidationError{}

// Validate checks the field values on UpdateTemplateBatchReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateTemplateBatchReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateTemplateBatchReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateTemplateBatchReplyMultiError, or nil if none found.
func (m *UpdateTemplateBatchReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateTemplateBatchReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateTemplateBatchReplyMultiError(errors)
	}

	return nil
}

// UpdateTemplateBatchReplyMultiError is an error wrapping multiple validation
// errors returned by UpdateTemplateBatchReply.ValidateAll() if the designated
// constraints aren't met.
type UpdateTemplateBatchReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateTemplateBatchReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateTemplateBatchReplyMultiError) AllErrors() []error { return m }

// UpdateTemplateBatchReplyValidationError is the validation error returned by
// UpdateTemplateBatchReply.Validate if the designated constraints aren't met.
type UpdateTemplateBatchReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateTemplateBatchReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateTemplateBatchReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateTemplateBatchReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateTemplateBatchReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateTemplateBatchReplyValidationError) ErrorName() string {
	return "UpdateTemplateBatchReplyValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateTemplateBatchReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateTemplateBatchReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateTemplateBatchReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateTemplateBatchReplyValidationError{}

// Validate checks the field values on UpdateTemplateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateTemplateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateTemplateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateTemplateRequestMultiError, or nil if none found.
func (m *UpdateTemplateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateTemplateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Type

	// no validation rules for Use

	// no validation rules for Content

	if len(errors) > 0 {
		return UpdateTemplateRequestMultiError(errors)
	}

	return nil
}

// UpdateTemplateRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateTemplateRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateTemplateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateTemplateRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateTemplateRequestMultiError) AllErrors() []error { return m }

// UpdateTemplateRequestValidationError is the validation error returned by
// UpdateTemplateRequest.Validate if the designated constraints aren't met.
type UpdateTemplateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateTemplateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateTemplateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateTemplateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateTemplateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateTemplateRequestValidationError) ErrorName() string {
	return "UpdateTemplateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateTemplateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateTemplateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateTemplateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateTemplateRequestValidationError{}

// Validate checks the field values on UpdateTemplateReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateTemplateReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateTemplateReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateTemplateReplyMultiError, or nil if none found.
func (m *UpdateTemplateReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateTemplateReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateTemplateReplyMultiError(errors)
	}

	return nil
}

// UpdateTemplateReplyMultiError is an error wrapping multiple validation
// errors returned by UpdateTemplateReply.ValidateAll() if the designated
// constraints aren't met.
type UpdateTemplateReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateTemplateReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateTemplateReplyMultiError) AllErrors() []error { return m }

// UpdateTemplateReplyValidationError is the validation error returned by
// UpdateTemplateReply.Validate if the designated constraints aren't met.
type UpdateTemplateReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateTemplateReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateTemplateReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateTemplateReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateTemplateReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateTemplateReplyValidationError) ErrorName() string {
	return "UpdateTemplateReplyValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateTemplateReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateTemplateReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateTemplateReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateTemplateReplyValidationError{}

// Validate checks the field values on CreateTemplateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateTemplateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateTemplateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateTemplateRequestMultiError, or nil if none found.
func (m *CreateTemplateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateTemplateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Type

	// no validation rules for Use

	// no validation rules for Content

	if len(errors) > 0 {
		return CreateTemplateRequestMultiError(errors)
	}

	return nil
}

// CreateTemplateRequestMultiError is an error wrapping multiple validation
// errors returned by CreateTemplateRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateTemplateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateTemplateRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateTemplateRequestMultiError) AllErrors() []error { return m }

// CreateTemplateRequestValidationError is the validation error returned by
// CreateTemplateRequest.Validate if the designated constraints aren't met.
type CreateTemplateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateTemplateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateTemplateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateTemplateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateTemplateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateTemplateRequestValidationError) ErrorName() string {
	return "CreateTemplateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateTemplateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateTemplateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateTemplateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateTemplateRequestValidationError{}

// Validate checks the field values on GetTemplateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTemplateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTemplateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTemplateRequestMultiError, or nil if none found.
func (m *GetTemplateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTemplateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetTemplateRequestMultiError(errors)
	}

	return nil
}

// GetTemplateRequestMultiError is an error wrapping multiple validation errors
// returned by GetTemplateRequest.ValidateAll() if the designated constraints
// aren't met.
type GetTemplateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTemplateRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTemplateRequestMultiError) AllErrors() []error { return m }

// GetTemplateRequestValidationError is the validation error returned by
// GetTemplateRequest.Validate if the designated constraints aren't met.
type GetTemplateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTemplateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTemplateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTemplateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTemplateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTemplateRequestValidationError) ErrorName() string {
	return "GetTemplateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetTemplateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTemplateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTemplateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTemplateRequestValidationError{}

// Validate checks the field values on ListTemplateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListTemplateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListTemplateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListTemplateRequestMultiError, or nil if none found.
func (m *ListTemplateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListTemplateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PageSize

	// no validation rules for PageNum

	// no validation rules for Order

	// no validation rules for SearchText

	// no validation rules for SearchField

	// no validation rules for Field

	// no validation rules for Cache

	if all {
		switch v := interface{}(m.GetFilterMap()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListTemplateRequestValidationError{
					field:  "FilterMap",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListTemplateRequestValidationError{
					field:  "FilterMap",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFilterMap()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListTemplateRequestValidationError{
				field:  "FilterMap",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListTemplateRequestMultiError(errors)
	}

	return nil
}

// ListTemplateRequestMultiError is an error wrapping multiple validation
// errors returned by ListTemplateRequest.ValidateAll() if the designated
// constraints aren't met.
type ListTemplateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListTemplateRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListTemplateRequestMultiError) AllErrors() []error { return m }

// ListTemplateRequestValidationError is the validation error returned by
// ListTemplateRequest.Validate if the designated constraints aren't met.
type ListTemplateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListTemplateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListTemplateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListTemplateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListTemplateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListTemplateRequestValidationError) ErrorName() string {
	return "ListTemplateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListTemplateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListTemplateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListTemplateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListTemplateRequestValidationError{}

// Validate checks the field values on ListTemplateReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListTemplateReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListTemplateReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListTemplateReplyMultiError, or nil if none found.
func (m *ListTemplateReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListTemplateReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetData() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListTemplateReplyValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListTemplateReplyValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListTemplateReplyValidationError{
					field:  fmt.Sprintf("Data[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Count

	if len(errors) > 0 {
		return ListTemplateReplyMultiError(errors)
	}

	return nil
}

// ListTemplateReplyMultiError is an error wrapping multiple validation errors
// returned by ListTemplateReply.ValidateAll() if the designated constraints
// aren't met.
type ListTemplateReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListTemplateReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListTemplateReplyMultiError) AllErrors() []error { return m }

// ListTemplateReplyValidationError is the validation error returned by
// ListTemplateReply.Validate if the designated constraints aren't met.
type ListTemplateReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListTemplateReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListTemplateReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListTemplateReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListTemplateReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListTemplateReplyValidationError) ErrorName() string {
	return "ListTemplateReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ListTemplateReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListTemplateReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListTemplateReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListTemplateReplyValidationError{}

// Validate checks the field values on TemplateDTO with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TemplateDTO) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TemplateDTO with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TemplateDTOMultiError, or
// nil if none found.
func (m *TemplateDTO) ValidateAll() error {
	return m.validate(true)
}

func (m *TemplateDTO) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	// no validation rules for CreatedBy

	// no validation rules for UpdatedBy

	// no validation rules for Name

	// no validation rules for Content

	// no validation rules for Type

	// no validation rules for Use

	// no validation rules for Default

	// no validation rules for Path

	if len(errors) > 0 {
		return TemplateDTOMultiError(errors)
	}

	return nil
}

// TemplateDTOMultiError is an error wrapping multiple validation errors
// returned by TemplateDTO.ValidateAll() if the designated constraints aren't met.
type TemplateDTOMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TemplateDTOMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TemplateDTOMultiError) AllErrors() []error { return m }

// TemplateDTOValidationError is the validation error returned by
// TemplateDTO.Validate if the designated constraints aren't met.
type TemplateDTOValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TemplateDTOValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TemplateDTOValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TemplateDTOValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TemplateDTOValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TemplateDTOValidationError) ErrorName() string { return "TemplateDTOValidationError" }

// Error satisfies the builtin error interface
func (e TemplateDTOValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTemplateDTO.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TemplateDTOValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TemplateDTOValidationError{}
