// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.27.1
// source: pb/healthy/healthy.v1.proto

package healthy

import (
	reflect "reflect"
	sync "sync"

	_ "github.com/Ccheers/protoc-gen-go-kratos-http/khttp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HealthyRequest) Reset() {
	*x = HealthyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_healthy_healthy_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthyRequest) ProtoMessage() {}

func (x *HealthyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_healthy_healthy_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthyRequest.ProtoReflect.Descriptor instead.
func (*HealthyRequest) Descriptor() ([]byte, []int) {
	return file_pb_healthy_healthy_v1_proto_rawDescGZIP(), []int{0}
}

type HealthyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 数据库状态 正常会返回 ok
	Mysql string `protobuf:"bytes,1,opt,name=mysql,proto3" json:"mysql,omitempty"`
	// redis状态 正常会返回 ok
	Redis string `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
}

func (x *HealthyReply) Reset() {
	*x = HealthyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_healthy_healthy_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthyReply) ProtoMessage() {}

func (x *HealthyReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_healthy_healthy_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthyReply.ProtoReflect.Descriptor instead.
func (*HealthyReply) Descriptor() ([]byte, []int) {
	return file_pb_healthy_healthy_v1_proto_rawDescGZIP(), []int{1}
}

func (x *HealthyReply) GetMysql() string {
	if x != nil {
		return x.Mysql
	}
	return ""
}

func (x *HealthyReply) GetRedis() string {
	if x != nil {
		return x.Redis
	}
	return ""
}

var File_pb_healthy_healthy_v1_proto protoreflect.FileDescriptor

var file_pb_healthy_healthy_v1_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x62, 0x2f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x2f, 0x68, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x6f,
	0x70, 0x73, 0x2e, 0x63, 0x6f, 0x64, 0x6f, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x2e, 0x68,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x6b, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x6d,
	0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x10, 0x0a, 0x0e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x3a, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x79, 0x73, 0x71, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6d, 0x79, 0x73, 0x71, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x64, 0x69, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x64, 0x69, 0x73, 0x32, 0x91, 0x01,
	0x0a, 0x07, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x12, 0x85, 0x01, 0x0a, 0x07, 0x48, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x79, 0x12, 0x2a, 0x2e, 0x6f, 0x70, 0x73, 0x2e, 0x63, 0x6f, 0x64, 0x6f,
	0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x2e, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x2e,
	0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x28, 0x2e, 0x6f, 0x70, 0x73, 0x2e, 0x63, 0x6f, 0x64, 0x6f, 0x2e, 0x6e, 0x6f, 0x74,
	0x69, 0x63, 0x65, 0x2e, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x48,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x24, 0xc2, 0xdb, 0xaa,
	0x03, 0x0f, 0x0a, 0x0d, 0x4a, 0x57, 0x54, 0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72,
	0x65, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0a, 0x12, 0x08, 0x2f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x7a, 0x42, 0x18, 0x5a, 0x16, 0x63, 0x6f, 0x64, 0x6f, 0x2d, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65,
	0x2f, 0x70, 0x62, 0x2f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pb_healthy_healthy_v1_proto_rawDescOnce sync.Once
	file_pb_healthy_healthy_v1_proto_rawDescData = file_pb_healthy_healthy_v1_proto_rawDesc
)

func file_pb_healthy_healthy_v1_proto_rawDescGZIP() []byte {
	file_pb_healthy_healthy_v1_proto_rawDescOnce.Do(func() {
		file_pb_healthy_healthy_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_healthy_healthy_v1_proto_rawDescData)
	})
	return file_pb_healthy_healthy_v1_proto_rawDescData
}

var file_pb_healthy_healthy_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_healthy_healthy_v1_proto_goTypes = []interface{}{
	(*HealthyRequest)(nil), // 0: ops.codo.notice.healthy.v1.HealthyRequest
	(*HealthyReply)(nil),   // 1: ops.codo.notice.healthy.v1.HealthyReply
}
var file_pb_healthy_healthy_v1_proto_depIdxs = []int32{
	0, // 0: ops.codo.notice.healthy.v1.Healthy.Healthy:input_type -> ops.codo.notice.healthy.v1.HealthyRequest
	1, // 1: ops.codo.notice.healthy.v1.Healthy.Healthy:output_type -> ops.codo.notice.healthy.v1.HealthyReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_healthy_healthy_v1_proto_init() }
func file_pb_healthy_healthy_v1_proto_init() {
	if File_pb_healthy_healthy_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_healthy_healthy_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_healthy_healthy_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_healthy_healthy_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_healthy_healthy_v1_proto_goTypes,
		DependencyIndexes: file_pb_healthy_healthy_v1_proto_depIdxs,
		MessageInfos:      file_pb_healthy_healthy_v1_proto_msgTypes,
	}.Build()
	File_pb_healthy_healthy_v1_proto = out.File
	file_pb_healthy_healthy_v1_proto_rawDesc = nil
	file_pb_healthy_healthy_v1_proto_goTypes = nil
	file_pb_healthy_healthy_v1_proto_depIdxs = nil
}
