// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pb/healthy/healthy.v1.proto

package healthy

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on HealthyRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *HealthyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthyRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in HealthyRequestMultiError,
// or nil if none found.
func (m *HealthyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return HealthyRequestMultiError(errors)
	}

	return nil
}

// HealthyRequestMultiError is an error wrapping multiple validation errors
// returned by HealthyRequest.ValidateAll() if the designated constraints
// aren't met.
type HealthyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthyRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthyRequestMultiError) AllErrors() []error { return m }

// HealthyRequestValidationError is the validation error returned by
// HealthyRequest.Validate if the designated constraints aren't met.
type HealthyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthyRequestValidationError) ErrorName() string { return "HealthyRequestValidationError" }

// Error satisfies the builtin error interface
func (e HealthyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthyRequestValidationError{}

// Validate checks the field values on HealthyReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *HealthyReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HealthyReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in HealthyReplyMultiError, or
// nil if none found.
func (m *HealthyReply) ValidateAll() error {
	return m.validate(true)
}

func (m *HealthyReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Mysql

	// no validation rules for Redis

	if len(errors) > 0 {
		return HealthyReplyMultiError(errors)
	}

	return nil
}

// HealthyReplyMultiError is an error wrapping multiple validation errors
// returned by HealthyReply.ValidateAll() if the designated constraints aren't met.
type HealthyReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HealthyReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HealthyReplyMultiError) AllErrors() []error { return m }

// HealthyReplyValidationError is the validation error returned by
// HealthyReply.Validate if the designated constraints aren't met.
type HealthyReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HealthyReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HealthyReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HealthyReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HealthyReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HealthyReplyValidationError) ErrorName() string { return "HealthyReplyValidationError" }

// Error satisfies the builtin error interface
func (e HealthyReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHealthyReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HealthyReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HealthyReplyValidationError{}
