# 项目元信息
metadata:
  name: "codo-notice"
  env: DEV
  gatewayPrefix: "http://codo-gateway:8888"

# 中间件
middleware:
  jwt:
    authKeyName: "auth_key"

# 服务注册
etcdRegistry:
  endpoints:
    - "127.0.0.1:2379"

# 可观测性相关
otel:
  trace:
    endpoint: "http://jaeger:14268/api/traces"
    insecure: true
  metric:
    enableExemplar: true
  log:
    level: debug

# 运输层相关
server:
  # 控制+通知接口配置
  http:
    addr: "0.0.0.0:8000"
    timeout: 5s
  # 第三方 webhook 接入
  thirdPartHook:
    network: "tcp"
    addr: "0.0.0.0:9001"
    timeout: 5s
  # metrics 配置
  prometheus:
    enable: true
    network: "tcp"
    addr: "0.0.0.0:8003"
    path: "/metrics"
  # golang pprof 配置
  pprof:
    enable: true
    network: "tcp"
    addr: "0.0.0.0:8004"

# 通知渠道回调配置
hook:
  larkCard:
    verificationToken: "xxx"
    encryptKey: "xxx"

# 通知渠道配置
notifyConfig:
  # email 配置
  email:
    host: smtp.feishu.cn
    port: 465
    user: codo@huanle.com
    password: xxx

  # 阿里通知配置
  aliyun:
    dxAccessId: LT____
    dxAccessSecret: obyElU_____
    dxSignName: CODO通知
    dxTemplate: SMS_20___
    dhAccessId: LTAI4F____
    dhAccessSecret: wFqdUb____
    dhTtsCode: TTS_21006____
    dhCalledShowNumber: "xxx"
    enable: true

  # 腾讯通知配置
  txyun:
    dxAccessId: xxx
    dxAccessSecret: xxx
    dxSignName: CODO通知
    dxTemplate: xxx
    dxAppId: xxx
    dhAccessId: xxx
    dhAccessSecret: xxx
    dhTemplate: xxx
    dhAppId: xxx
    enable: true

  # 飞书配置
  fsapp:
    appId: "xxx"
    appSecret: "xxxxx"

  # 钉钉通知配置
  ddapp:
    appId: xxx
    appSecret: xxx-xx
    agentId: "xxx"

  # 微信通知配置
  wxapp:
    agentId: 112233
    agentSecret: xxx
    cropId: xxx

# 数据库和缓存相关
data:
  database:
    link: "root:xxxx@tcp(127.0.0.1:3306)/codo-notice?loc=Local&charset=utf8mb4&parseTime=True"
    debug: true
    prefix: codo_
  redis:
    addr: 127.0.0.1:6379
    readTimeout: 0.2s
    writeTimeout: 0.2s
    password:

# 用户同步
userSync:
  gatewayAPIPrefix: ""
  gatewayToken: ""